# Use the official Python image from the Docker Hub
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Upgrade pip and install the dependencies from requirements.txt
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose port 8000 to the outside world
EXPOSE 8000

# Define the environment variables for Flask
ENV FLASK_APP=Screener_Webapp.py
ENV FLASK_ENV=production

# Run Gunicorn to serve the Flask app on container startup
CMD ["gunicorn", "--workers", "3", "--bind", "0.0.0.0:8000", "Screener_Webapp:app"]
