# Specify the python provider and set the version to 3.10
[provider]
name = "python"
version = "3.10"

# Install dependencies from requirements.txt
[phases.install]
commands = [
    "pip install -r requirements.txt"
]

# Start the application with Gunicorn
[phases.start]
commands = [
    "pip show gunicorn",  # Check if Gunicorn is installed
    "gunicorn --workers 3 --bind 0.0.0.0:8000 Screener_Webapp:app"
]

# Set environment variables for Flask
[variables]
FLASK_APP = "Screener_Webapp.py"
FLASK_ENV = "production"