# Specify the python provider and the Python version you're using
[provider]
name = "python"
version = "3.10"

# Install phase: Install required dependencies using pip
[phases.install]
commands = [
  "pip install -r requirements.txt"
]

# Start phase: Use Gunicorn to serve your Flask app
[phases.start]
commands = [
  "gunicorn --workers 3 --bind 0.0.0.0:8000 Screener_Webapp:app"
]

# Any additional environment variables required
[variables]
FLASK_APP = "Screener_Webapp.py"
FLASK_ENV = "production"