# Specify the provider and Python version
[provider]
name = "python"
version = "3.10"

# Setup phase to install dependencies
[phases.install]
commands = [
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

# Start phase to run Gunicorn
[phases.start]
commands = [
  "python3 -m gunicorn --workers 3 --bind 0.0.0.0:8000 Screener_Webapp:app"
]

# Additional environment variables
[variables]
FLASK_APP = "Screener_Webapp.py"
FLASK_ENV = "production"