# Specify the python provider and set the version to 3.10
[provider]
name = "python"
version = "3.10"

# Install phase: Install dependencies from requirements.txt
[phases.install]
commands = [
    "python3 -m ensurepip --upgrade",  # Ensure pip is installed and upgraded
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r requirements.txt"  # Install all dependencies, including gunicorn
]

# Start the application using Gunicorn
[phases.start]
commands = [
    "python3 -m gunicorn --workers 3 --bind 0.0.0.0:8000 Screener_Webapp:app"  # Make sure to use the python3 environment
]

# Environment variables for Flask
[variables]
FLASK_APP = "Screener_Webapp.py"
FLASK_ENV = "production"