# Specify the provider and version for Python
[provider]
name = "python"
version = "3.10"

# Setup phase: install dependency
[phases.setup]
commands = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

# Start phase: run the application with Gunicorn
[phases.start]
commands = [
  "gunicorn --workers 3 --bind 0.0.0.0:8000 Screener_Webapp:app"
]

# Environment variables
[variables]
FLASK_APP = "Screener_Webapp.py"
FLASK_ENV = "production"