# Specify the python provider and the Python version you're using
[providers.python]
version = "3.10"

# Setup phase: Install required dependencies using pip
[phases.setup]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

# Start phase: Use Gunicorn to serve your Flask app
[phases.start]
cmd = "gunicorn --workers 3 --bind 0.0.0.0:8000 Screener_Webapp:app"

# Environment variables for Flask
[variables]
FLASK_APP = "Screener_Webapp.py"
FLASK_ENV = "production"