# Specify the providers
providers = ["python"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.start]
cmds = [
    "gunicorn --workers 3 --bind 0.0.0.0:8000 Screener_Webapp:app"
]

[variables]
FLASK_APP = "Screener_Webapp.py"
FLASK_ENV = "production"