# Specify the python provider and set the version to 3.10
[provider]
name = "python"
version = "3.10"

[phases.setup]
commands = [
    "pip install --upgrade pip"
]

[phases.install]
commands = [
    "pip install -r requirements.txt"
]

[phases.start]
commands = [
    "gunicorn --workers 3 --bind 0.0.0.0:8000 Screener_Webapp:app"
]

[variables]
FLASK_APP = "Screener_Webapp.py"
FLASK_ENV = "production"